language: node_js
node_js:
  - "stable"
cache:
directories:
  - node_modules

before_script:
  - npm install -g create-react-app
 
script:
  - npm install
  - npm run build

deploy:
  provider: s3
 
  bucket: "lmsfrontend"
  skip_cleanup: true
  region: "ap-southeast-2"
  acl: public_read
  local_dir: build
